### ISSUE TITLE
sub converter doesnt work

### ISSUE THREAD

**Issue by ghost** [LBRYFoundation/Watch-on-LBRY#104]
**Describe the bug**
the converter is stuck at 100% and it doesnt show urls to the odysee channels  
**To Reproduce**
1. Go to 'subscription converter'
2. Click on 'Start Conversion!'

**Expected behavior**
list of links which directs to odysee channels

**Screenshots**
![2022-02-13_17-55](https://user-images.githubusercontent.com/61807003/153761401-71a0c5fc-24b9-4228-bf35-6efeca5a00be.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 96

**Comment by kodxana** [comment]
What API provider? Cause mine is currently off.

**Comment by ghost** [comment]
@kodxana what? idk what is that. i am using the add on by Madiator2011

**Comment by kodxana** [comment]
I was moving DNS stuff thats why API wasn't working but now it should work fine. BTW I'm Madiator :)

**Comment by Relected** [comment]
@kodxana well  hello there, also it still doesnt work even after reinstalling the extension

**Comment by ghost** [comment]
still stuck at 100%, i think youtube changed something on the exported file

**Comment by kodxana** [comment]
Can you check network tab and see if you get any errors?

**Comment by ghost** [comment]
@kodxana when using madiator it says: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://scrap.madiator.com/api/get-lbry-channel?v=2&url=**{channel-id}** (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 429.

when using odysee it does nothing.

**Comment by kodxana** [comment]
Should be fixed now. Was moving domain to new reverse proxy and it was not adding CORD header and that was making issues.

**Comment by kodxana** [comment]
@Relected If you want to support my work fell free to leave a tip at https://open.lbry.com/@Madiator2011:e/LBRYNexus:f

**Comment by ghost** [comment]
@kodxana ok so now it says this whenever i try  to convert subs

429 Too Many Requests

50 per 1 hour

only 4 channels appeared, but i am 100% certain that there is more than that

**Comment by devbrones** [comment]
@Relected this is my bad, i implemented a cooldown in the api so it would not get flooded... Cant push a new version atm. Will later...

**Comment by devbrones** [comment]
@kodxana does the converter use wol-api too?

**Comment by kodxana** [comment]
> @kodxana does the converter use wol-api too?

Yes if user select my hosted API.

**Comment by devbrones** [comment]
@kodxana what origin header does the extension have? Would mb be possible to add an exception for the plugin to let it circumvent cooldowns...

**Comment by kodxana** [comment]
I use nginx proxy and allowing cors from anywhere

**Comment by devbrones** [comment]
So there is no way of differentiating a standard request from a sub conv request?

**Comment by devbrones** [comment]
Cooldown fixed in [commit 055fa90](https://github.com/devbrones/wol-api/commit/055fa90b69ad8672d1f897cc072f558fd6ee58cf)

**Comment by ghost** [comment]
@devbrones does that means that I can convert in peace now?
edit: it now always stuck at 1.8% first try when choosing madiator as a URL resolver, and then the console sends hundreds of errors

like, literally hundreds of these

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://scrap.madiator.com/api/get-lbry-channel?v=2&url={channel_id}. (Reason: CORS request did not succeed). Status code: (null).

and also this GET https://scrap.madiator.com/api/get-lbry-channel?v=2&url={channel_id}
CORS Missing Allow Origin

**Comment by kodxana** [comment]
I have updated the api with new limit. Try now.
Also what version of plugin you have?

**Comment by ghost** [comment]
@kodxana im using 1.7.7


also the converter is stuck at 10% now

**Comment by kodxana** [comment]
@devbrones

**Comment by kodxana** [comment]
@Relected I think I know what is happening.
My current setup is: Extension ------> Reverse Proxy ------> API Server
API had hardcoded limit of 200 calls per day. Issue is that all request goes via reverse proxy and that makes so my ip send requests to api server and it was making my proxy being ratelimited. Now I edited code to add huge limit so it should work now fine.

**Comment by kodxana** [comment]
Published fix https://github.com/LBRYFoundation/Watch-on-LBRY/commit/bd33aa833f780b15c47bb9b9030921c1d451aa29
Soon wil be out on firefox with version 1.7.8

**Comment by ghost** [comment]
@kodxana i have updated the extension to the latest version now (1.7.8), It's now always stuck at exactly 88.6% every time

**Comment by kodxana** [comment]
Error logs?

**Comment by devbrones** [comment]
@kodxana no need to change rate limit! pull the newest version of wol-api

**Comment by devbrones** [comment]
it should fix proxy ip passthrough

**Comment by ghost** [comment]
@kodxana idk what this is, its stuck like that
![odysee sub](https://user-images.githubusercontent.com/61807003/156886906-8a7f9d5b-b412-406a-801d-5e1d6eab6169.png)

**Comment by devbrones** [comment]
@Relected probably due to an ongoing update

**Comment by kodxana** [comment]
404 is return when the Channel is not found by API

**Comment by ghost** [comment]
@kodxana well its still stuck at this percentage and it doesnt seem to progress at all, i left it for 15 minutes and its still the same, at least it should show the channels the have been found while its converting

**Comment by kodxana** [comment]
> @kodxana well its still stuck at this percentage and it doesnt seem to progress at all, i left it for 15 minutes and its still the same, at least it should show the channels the have been found while its converting

Send me your subscription file to admin@madiator.com

**Comment by ghost** [comment]
@kodxana i fell a lil but uncomfortable sending you the whole file, can i send just a small portion of it instead to the email? or even leave a bit of it in this issue?

**Comment by kodxana** [comment]
What about remote call via Jitsi, Discord etc?

**Comment by ghost** [comment]
@kodxana thats fine, my discord is rTerm#7406
