### ISSUE TITLE
"Watch on YouTube" button

### ISSUE THREAD

**Issue by alexrelis** [LBRYFoundation/Watch-on-LBRY#105]
First off, thank you to the developers of this extension. I use it daily and it has made the switch to alternative platforms a lot easier.

Normally if I click on a YouTube video I want to watch, I use this extension to check to see if it's available on Odysee (I have automatic redirection turned off) and watch it there. The problem is that when in Odyssey, sometimes I want to see a video's YouTube comments.
I'd really like it if there was a Watch on YouTube button on Odyssey videos. It sounds counterintuitive, but sometimes I just want to see what the people on YouTube are saying and I'd imagine that because the extension already knows which YouTube accounts are synced with Odysee, it already knows which Odysee accounts are synced with YouTube.

**Comment by kodxana** [comment]
Do not think it's good idea but you can fork the code and do it reverse :)
