### ISSUE TITLE
Add an option to make the "Watch on Odysee" button open in a new tab instead of replace the current YouTube tab.

### ISSUE THREAD

**Issue by alexrelis** [LBRYFoundation/Watch-on-LBRY#106]
Just wanted to say thanks to the devs of this extension for making it easy for me to migrate to a new and growing platform.

Every time I see a YouTube video, I use this extension (I have auto redirection disabled) to check to see if the video is available on Odysee and I watch it there. The only issue is that sometimes I want to see the YouTube comments while watching the video on Odysee, but when I click on the "Watch on Odysee" button, the Odysee page is loaded over the YouTube page. As a result, I have to right-click and open in new tab and I often forget to do this.

I would like it if there was an option to make the "Watch on Odysee" button open in a new tab instead of replace the current YouTube tab. That way I could have both the YouTube tab open to view comments and watch the video on Odysee and view comments in there as well.

An alternative solution would be to make the video open in a new tab with auto redirection is enabled as well. That would be a great solution for me because I don't have to press the "Watch on Odysee" button every time.

This feature request is adjacent to this other feature request I've submitted: https://github.com/LBRYFoundation/Watch-on-LBRY/issues/105#issue-1146449512

**Comment by nomadshiba** [comment]
Hmm, the reason it is replacing the current tab is so people can choose to open in new tab by using the middle mouse button. at least thats how i use it. just like you open the channel in new tab while video is playing etc.

but you are right it might be problematic on redirect and for people who are used to using left button. i can add an option to make it so it opens it on new tab always.

**Comment by alexrelis** [comment]
Yay!!!
