### ISSUE TITLE
Doesn’t Work for One Specific Video

### ISSUE THREAD

**Issue by FlorianWendelborn** [LBRYFoundation/Watch-on-LBRY#112]
**Describe the bug**
<https://www.youtube.com/watch?v=AWspiqNvQfM> Watch on Odysee doesn’t work

**To Reproduce**
1. Go to https://www.youtube.com/watch?v=AWspiqNvQfM
2. Click on Watch on Odysee
3. Land on <https://odysee.com/can-you-(always)-pair-an-equal-number-of:9b05d7be2d4d90782a425b856ca843d0415ff575>, which is 404

**Expected behavior**

Should land on <https://odysee.com/@ZachStar:0/red-and-blue-pairing-puzzle:1>

**Screenshots**

![image](https://user-images.githubusercontent.com/1133858/165755904-ab4a2fb5-e063-4dcb-9ea6-774d10c7bd7a.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser Firefox Developer Edition
 - Version 100.0b9 64-bit

**Additional context**

N/A

**Comment by kodxana** [comment]
<img width="336" alt="Zrzut ekranu 2022-04-28 o 15 05 11" src="https://user-images.githubusercontent.com/16674412/165760313-9fdf4c6f-af6b-4f7f-804d-766e5a0ea439.png">

**Comment by FlorianWendelborn** [comment]
@kodxana Interesting, in that case is it possible for the extension to detect that the video doesn’t exist anymore and just stay on YouTube instead?
