### ISSUE TITLE
Open LBRY.TV links and open.lbry links in desktop app

### ISSUE THREAD

**Issue by professor-cowboy** [LBRYFoundation/Watch-on-LBRY#13]
open links sending to lbry.tv in the desktop app.

**Comment by kodxana** [comment]
Do you mean that if user press lbry.tv link in LBRY App you want it to be opened in LBRY App instead of it :)

**Comment by professor-cowboy** [comment]
yeah i just want to redirect anything going to lbry.tv to the lbry app instead.
