### ISSUE TITLE
Setting that allows to add new invidious instances

### ISSUE THREAD

**Issue by K0SS4** [LBRYFoundation/Watch-on-LBRY#136]
I would love to add my own invidious instance to the list of locally supported sites. Kinda like in sponsor block where we have a textbox for a url and then it just asks for permission to that site. I know that allowed invidious instances are [there](https://github.com/LBRYFoundation/Watch-on-LBRY/blob/master/src/settings/index.ts#L160) but it would be much easier if I could just add it in the gui without recompiling the extension.

**Comment by kodxana** [comment]
It would not be possible unless I set manifest permission to allow all websites with my lead to privacy risk and issues.

**Comment by K0SS4** [comment]
I'm no web developer but firefox(I don't know how it is with chromium based browsers) asks if I want to allow SponsorBlock to access sites that I provide as "3rd party invidious instances" in extension's settings so it doesn't allow all sites by default I guess. It's also possible that I misunderstood you :)

**Comment by nomadshiba** [comment]
to be able to support custom user defined invidious instances, we need our to allow our extension to have access to all of the sites you visit. some users might find this dangerous.
so it can be done. it just some users might find this dangerous or spying even thought we dont have any code that is doing that.
but it still can be done.

**Comment by K0SS4** [comment]
Okay. I understand now, thanks. Gonnaa try to compile it with my instance then. Closing the issue
