### ISSUE TITLE
Redirecting only works after refreshing the youtube page

### ISSUE THREAD

**Issue by ghost** [LBRYFoundation/Watch-on-LBRY#16]
When I click on a video I know is available on lbry.tv the extension doesn't redirect me right away. Instead, I have to refresh the page for the extension to work.

**To Reproduce**
1. Go to youtube.com
2. Click on a video that is available on LBRY (and see that it doesn't redirect you)
3. Then refresh the page and you will get redirected properly.

I've recorded the whole process, the recording is available with the link below (when the extension didn't redirect me I refreshed the page but it's not quite visible).
https://open.lbry.com/bugreport-for-watchonlbry-plugin-341431431:e?r=6SkDfKCh1chWTCXT9mjDDf3oLEVt2gbz

I'm using Chrome 80.0.3987.163 on macOS Catalina 10.15.4 (19E287).
I have "enable redirection = on" and "where would you like to redirect = LBRY.tv"

**Comment by kevinmcfarlane** [comment]
It was working for me until today. It worked this morning and has now stopped - even after a soft and hard refresh.

**Comment by pmilic021** [comment]
for me it never worked at all, not sure how to fix it

**Comment by kodxana** [comment]
@pmilic021 Could you reach me on LBRY Discord?

**Comment by kodxana** [comment]
@JanTheDeveloper @kevinmcfarlane Can you try reinstall plugin from store?

**Comment by pmilic021** [comment]
@kodxana whats your username there? but cant find you by this one
