### ISSUE TITLE
Support for insidious 

### ISSUE THREAD

**Issue by yisraeldov** [LBRYFoundation/Watch-on-LBRY#20]
It would be nice if it also works for for invidious

**Comment by kodxana** [comment]
Do you know if invidious uses that same format of URL as YouTube?

**Comment by kodxana** [comment]
@yisraeldov We could possibly add support for invidio.us instance :)

**Comment by kodxana** [comment]
Done :) https://github.com/kodxana/Watch-on-LBRY/commit/e3eeff4dac247b99e5ec10de9ab6d43672e932d6

**Comment by L1pE** [comment]
Invidio.us is no longer an working instance since September 1st 2020, it's merely a page that lists other instances now. Could there be added support for other instances as an option like, say, SponsorBlock does it?
