### ISSUE TITLE
Open lbry protocol links in either lbry.tv or desktop client. 

### ISSUE THREAD

**Issue by JobDestroyer** [LBRYFoundation/Watch-on-LBRY#24]
If you copy a lbry link, and paste it in a browser, you'll probably just search it. 

I'd like to see an extension to make it open it in the lbry client or in lbry.tv

![image](https://user-images.githubusercontent.com/67790348/88394041-b9877800-cd8c-11ea-8dbc-03e4423fc4d6.png)

**Comment by kodxana** [comment]
Duplicate https://github.com/kodxana/Watch-on-LBRY/issues/13

**Comment by JobDestroyer** [comment]
Hello, I don't think this is a duplicate, as that seems to be a case of trying to open lbry.tv links in the desktop app, I'm referring to lbry://whatever links in either the desktop app or lbry.tv

**Comment by kodxana** [comment]
Probably not possible unless you setup system to handle lbry:// links.

**Comment by kauffj** [comment]
@kodxana can't the plugin read what the user has typed into the omnibar?

**Comment by kodxana** [comment]
@kauffj aparently there is a API stuff for omnibox but will need to look after it. https://developer.chrome.com/extensions/omnibox
