### ISSUE TITLE
Support for Odysee (or other possible frontend options)

### ISSUE THREAD

**Issue by guille-bada** [LBRYFoundation/Watch-on-LBRY#29]
**Is your feature request related to a problem? Please describe.**
The addon is great and works wonderfully, but lately I've been using [Odysee](https://odysee.com/) as a LBRY frontend as it looks slicker and overall works better.
As of now, each time I'm redirected through the addon, I have to edit the url and swap the lbry.tv part for odysee.com (the rest of the url stays the same)

**Describe the solution you'd like**
Aside from choosing to be redirected to lbry.tv or the LBRY app, having the option to choose Odysee or any other frontend that may pop up in the future would be great.

**Comment by kodxana** [comment]
Included in https://github.com/LBRYFoundation/Watch-on-LBRY/pull/34 :)
