### ISSUE TITLE
Add support for redirecting invidio.us instances

### ISSUE THREAD

**Issue by wuniversales** [LBRYFoundation/Watch-on-LBRY#36]
Please add support for redirecting invidio.us instances, I currently use invidius instances for privacy reasons, it would be good to add support.
Instances: https://invidio.us
Thanks

**Comment by kodxana** [comment]
As of September 1st 2020, invidio.us has closed down.

**Comment by wuniversales** [comment]
But not their instances...

**Comment by ghost** [comment]
> 
> 
> As of September 1st 2020, invidio.us has closed down.

invidio.us was one instance. The project is still active and has several functioning instances.

**Comment by nomadshiba** [comment]
currently we support:
- yewtu.be
- vid.puffyan.us
- invidio.xamh.de 
- invidious.kavin.rocks

https://github.com/LBRYFoundation/Watch-on-LBRY/blob/63a251c0ae71e6856f8cc2f699ef23d4b8364ff9/src/settings/index.ts#L129
