### ISSUE TITLE
Redirect lbry.tv to odysee.com and visa versa

### ISSUE THREAD

**Issue by Neurognostic** [LBRYFoundation/Watch-on-LBRY#37]
**Describe the solution you'd like**
Add an option to redirect `lbry.tv` URLs to `odysee.com` and visa-versa.

This will allow users to more easily use the LBRY client of their choice no matter the URLs that are shared with them.

**Comment by Neurognostic** [comment]
Another related feature would be to redirect `lbry.tv` and/or `odysee.com` links to the LBRY desktop client.

**Comment by kodxana** [comment]
Ah your sorry that I haven't seen that issue later but it should be fixed anyway :)
