### ISSUE TITLE
Instead of redirect. Show a popup from the extension icon.

### ISSUE THREAD

**Issue by CyberFoxHax** [LBRYFoundation/Watch-on-LBRY#38]
It's a little cumbersome to have to switch redirect on and off when trying to navigate back. Instead i think it would be better to have a little box slide out offering to open in lbry.tv. That way i can finish do what i wanted to do on YouTube before moving on.

Lbry doesn't do playlists yet, thus navigating back to YouTube and clicking next and then clicking the slideout. Anyway, good work on this. Fight the powa!

**Comment by kodxana** [comment]
Fixed in https://github.com/LBRYFoundation/Watch-on-LBRY/pull/70
Now you can set enable redirect to off and you will see button on YouTube if the video is on LBRY :)
