### ISSUE TITLE
How do you export subs? The sub manager doesn't have an export button at the bottom. Thanks

### ISSUE THREAD

**Issue by Steve-just-steve** [LBRYFoundation/Watch-on-LBRY#41]
How do you export subs? The sub manager doesn't have an export button at the bottom. Thanks

**Comment by Aenigma** [comment]
It looks like YouTube totally got rid of the ability to export your subscription as an OPML file. You used to get the file when you hit https://www.youtube.com/subscription_manager?action_takeout=1 but that just redirects to the subscription page.

Thanks for bringing it to our attention! We'll probably have to find a new way to get the subscription data now.

**Comment by kodxana** [comment]
Only way left is to use google API to pull subscriptions. PS: Or mayby not :)

**Comment by PeterKW** [comment]
https://takeout.google.com/takeout/custom/youtube?pli=1 lets the user export subscriptions as a JSON file which should hopefully be parseable "Subscriptions - Your channel subscriptions. JSON A machine-readable format"

![image](https://user-images.githubusercontent.com/13779157/99155141-3b3d4180-26ad-11eb-8d4f-f0d7e16ed482.png)

**Comment by Aenigma** [comment]
I've actually already have code to use this JSON format on a local branch. But we're right now considering if we can make this feature available without installing the extension.

**Comment by kodxana** [comment]
Fixed in https://github.com/LBRYFoundation/Watch-on-LBRY/pull/43
