### ISSUE TITLE
Documentation: How exactly does this plugin know what to redirect and where?

### ISSUE THREAD

**Issue by Neurognostic** [LBRYFoundation/Watch-on-LBRY#42]
**Is your feature request related to a problem? Please describe.**
Could you please add a high level overview to the README for how this plugin knows how to redirect YouTube URLs to LBRY URLs?

I am asking because it does not always behave as expected. Sometimes channels that normally redirect won't (even though the video exists on both platforms). Some channels video's won't redirect because they upload to LBRY first instead of YouTube first, but their YouTube channel home page will correctly redirect.

**Describe the solution you'd like**
Depending on how the plugin works, maybe there could be a user contributed list of redirects, similar to how ad blocking plugin communities maintain lists of hostnames to block or maybe the algorithm just needs to be improved to dynamically redirect the example cases above.

**Comment by kodxana** [comment]
Plugin uses LBRY API that is connected to LBRY YouTube sync program. This way we can verify witch channels/videos ID'S are synced with LBRY. It won't work if user upload content manually cause it's not saved in YouTube sync database :)

**Comment by kodxana** [comment]
About community list might be more complex thing to do cause we would need to verify if person X on YouTube is person X on LBRY. So we do not get situation that someone not try to steal someone's channel traffic.

**Comment by Neurognostic** [comment]
Hmm, I can see how it would be difficult to verify that redirects go to the claim controlled by the content creator.

I wonder if [LBRY's naming system](https://lbry.com/faq/naming) could be leveraged here so that only `communtiy` names are accepted for redirects and therefore only the claim with the most LBC will actually resolve.

https://lbry.com/faq/naming
https://lbry.tech/spec#claimtrie

**Comment by Sukid** [comment]
That would almost have to be its own service, but I do think something like that is needed. Really, LBRY/Odysee really do need to have more account linking features just so someone CAN verify that the content they're uploading is theirs and not stolen from some other youtuber.

**Comment by othello777** [comment]
Couldn't one verify their youtube identity via a sign in portal? I have a manually synced LBRY account and I feel like I'm missing out on so much traffic from not being in the LBRY Sync API database

**Comment by nomadshiba** [comment]
@othello777 what kind of service do you think. we can let you login with two channels to verify that you own the channels.
then in what way we match the videos in the channels together? 
- we can try to guess based on title and release date?
- or would it be better if you had an interface to match videos manually?
- hmm or maybe when you add lbry/odysee link to description of the yt video?

also this wouldnt work with odysee api, this would only work with our madiator finder api.

**Comment by othello777** [comment]
@DeepDoge you'd need an interface for the creator to match them manually but an "auto match" feature would also come in very handy. I would personally use a mixture of both on my channel.
The 3rd option could work too and is interesting. I am currently working with the developer of an offline sync program and the most annoying thing for me as a content creator is that people like myself who use this extension likely wouldn't know I have an odysee channel.

**Comment by nomadshiba** [comment]
@othello777 well 3rd option would be the easiest to implement. and if we skip the part that you have to verify you own the both channels. it can run without asking to the api. think of it like we just convert the link in the description to a button.

for your offline sync app, you would edit the yt description to add the odysee link and it would work with the extension

**Comment by devbrones** [comment]
sorry if i am late to the party :D i am the developer behind the API that Watch On LBRY uses to redirect from YouTube to LBRY. (WOLAPI https://github.com/devbrones/wol-api)

Perhaps a browser extension could be created that checks if a user is logged into and therefore the owner of a youtube account and then automatically syncs video titles to a database together with some form of uid. these titles could then be manually matched or searched for using odysees api or perhaps searched for using machine learning :D who knows.

This sounds like an interesting project to me so perhaps i will make an attempt at some point.

**Comment by kodxana** [comment]
> sorry if i am late to the party :D i am the developer behind the API that Watch On LBRY uses to redirect from YouTube to LBRY. (WOLAPI https://github.com/devbrones/wol-api)
> 
> Perhaps a browser extension could be created that checks if a user is logged into and therefore the owner of a youtube account and then automatically syncs video titles to a database together with some form of uid. these titles could then be manually matched or searched for using odysees api or perhaps searched for using machine learning :D who knows.
> 
> This sounds like an interesting project to me so perhaps i will make an attempt at some point.

Though we switched API implementation :)

**Comment by devbrones** [comment]
@kodxana oh really? interesting. thanks for letting me know that
very professional!:smiley:

**Comment by devbrones** [comment]
might want to tell a developer that you worked with who continuously developed a product for you for around two months that you have chosen to go a different route and that you no longer will be using the product. instead of wasting time that said developer could have spent on other projects instead of optimizing code that never will be used 👍👍

**Comment by devbrones** [comment]
:troll:

**Comment by othello777** [comment]
did anything get added? this is still something that would be good to have.

It looks like odysee just created their own "watch on odysee" extension so I wonder if this will become more confusing in the future.

**Comment by kodxana** [comment]
> did anything get added? this is still something that would be good to have.
> 
> 
> 
> It looks like odysee just created their own "watch on odysee" extension so I wonder if this will become more confusing in the future.

Watch on LBRY has much more futures and Watch on Odysee is Watch on LBRY with futures removed.
