### ISSUE TITLE
Swap lbry:// to open.lbry.com

### ISSUE THREAD

**Issue by kodxana** [LBRYFoundation/Watch-on-LBRY#5]
**Describe the solution you'd like**
Allow plugin to detect lbry:// adresses and turn them into open.lbry.com format.

**Comment by kodxana** [comment]
Can probably help :) https://github.com/seanyesmunt/lbry-link

**Comment by ghost** [comment]
Dibs

**Comment by Yamgirly** [comment]
@tuxnull are you still working on this?

**Comment by kodxana** [comment]
@Yamboy1 No he is not :)

**Comment by Yamgirly** [comment]
Similar feature added in #12.

**Comment by Yamgirly** [comment]
Request for close @kodxana
