### ISSUE TITLE
Should default to odysee.com instead of lbry.tv

### ISSUE THREAD

**Issue by nixfu** [LBRYFoundation/Watch-on-LBRY#53]
I know you can change the default destination via the popup menu, but at this point, on any new installs, the extension should default to odysee.com instead of lbry.tv.  Odysee.com has overtaken lbry.tv as the preferred front end for most users.

**Comment by Aenigma** [comment]
You'll be happy to know that this is already done and you should be able to see it when we next publish.

**Comment by jelabarre59** [comment]
I have v1.7.2 (May 1, 2021) and it still redirects to LBRY rather than Odysee, and no configuration options in the plugin

**Comment by kodxana** [comment]
![image](https://user-images.githubusercontent.com/16674412/118106219-a7d79580-b3dd-11eb-88d6-f333c54eacf1.png)
You can set here to redirect to Odysee. Just press plugin icon in your taskbar.

**Comment by jelabarre59** [comment]
Ah, I had been looking in the Extensions configuration screen for the settings.

**Comment by kodxana** [comment]
Fixed in https://github.com/LBRYFoundation/Watch-on-LBRY/pull/70
