### ISSUE TITLE
Desktop App redirect does not work on KDE / Chrome

### ISSUE THREAD

**Issue by henk717** [LBRYFoundation/Watch-on-LBRY#55]
After some troubleshooting i have finally managed to track down that the extension is the cause of the failure to open the LBRY desktop links when it is set to desktop mode when KDE is used in combination with a chrome based browser (Might happen on Firefox to, would need to be tested).

The error i get will be the KIO Client saying "unknown host lbry: Host not found.", if i make a tinyurl that redirects to a lbry link and i then navigate to this url the link works great, this will also work great if i manually open lbry:// links in the terminal. This means that the LBRY appimage is correctly registered on my system, and the browser is capable of opening [lbry:// links](lbry://@lbry).

Unfortunately i do not currently have any means to detect which link the extention is trying to open, but my assumptions are that the generated link is parsed incorrectly or at least not how the link would normally be generated.

Testing steps would involve running KDE distribution in combination with a chrome based browser and the LBRY appimage installed (This can be a live system), installing the extension and getting it to redirect to the desktop app.

**Comment by kodxana** [comment]
Published update to web store and firefox. Should be out soon.
