### ISSUE TITLE
Redirection no longer working on Brave

### ISSUE THREAD

**Issue by theJoshMuller** [LBRYFoundation/Watch-on-LBRY#56]
**Describe the bug**
A couple weeks ago redirection was working fine on my Brave installation, but sometime recently it has stopped working. The plugin says it's **on**, but no redirection is happening. I attempted switching between lbry.tv and odysee.com, as well as turning the plugin on/off, but no luck. Seems to work fine on Firefox. I attempted using the plugin on a new Brave "person"/"account"/"workspace" (with no plugins installed), and it didn't work there either, so it doesn't seem to be a plugin conflict. 

**To Reproduce**

1. Open Brave
2.  Navigate to a YouTube video synced to the LBRY network (i.e. [this one](https://www.youtube.com/watch?v=bBC-nXj3Ng4))

**Expected behavior**
Redirection to equiv video on LBRY network (i.e. [this one](https://lbry.tv/@3Blue1Brown:b/ever-wonder-how-bitcoin-and-other:1) from the example above).

**Desktop:**
 - OS: Manjaro - 5.10.23-1-MANJARO kernel
 - Browser: Brave
 - Version: Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)

**Comment by henk717** [comment]
Also currently noticing this on Brave, but only partially. Using the App setting will get it to attempt to redirect to the APP (Which triggers the bug i filed yesterday) if you are on a Odysee or LBRY page. But the youtube redirects and the website button are no longer working. This might be broader to other browsers than brave as this could be a YouTube or Chromium issue.

**Comment by cytsunny** [comment]
Same here is ubuntu 20.04

And I have the redirect not working on both Brave and Chrome.

**Comment by Aenigma** [comment]
So the problem results in a CORS related issue. We can workaround this by by doing the fetch in the background script and then making sending the data back to the content scripts.

**Comment by TheGhostHybrid** [comment]
Can confirm that redirection does not work on Vivaldi. Currently running Manjaro, same version as OP.

**Comment by henk717** [comment]
Did this fix land in the public build yet? Because i am still not getting any redirects or Watch on LBRY buttons on YouTube.

**Comment by theJoshMuller** [comment]
Same as @henk717 . Problem persists in Brave

**Comment by kodxana** [comment]
> Did this fix land in the public build yet? Because i am still not getting any redirects or Watch on LBRY buttons on YouTube.



> Same as @henk717 . Problem persists in Brave

Published update to web store and firefox. Should be out soon.

**Comment by theJoshMuller** [comment]
Confirming: current version of plugin on [Chrome Web Store](https://chrome.google.com/webstore/detail/watch-on-lbry/jjmbbhopnjdjnpceiecihldbhibchgek?hl=en) has solved this problem 👍🏽
