### ISSUE TITLE
Subscription Converter feature doesn't seem to work

### ISSUE THREAD

**Issue by AIVAS001** [LBRYFoundation/Watch-on-LBRY#64]
**Describe the bug**
Subscription Converter feature doesn't seem to work

**To Reproduce**
Upload either CSV (Youtube now exports CSVs) or JSON (after converting CSV to JSON)

**Expected behavior**
There should be a list of those YT channels I subscribe to that also appear on LBRY

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Vivaldi
 - Version: Vivaldi: 4.1.2369.21 (Stable channel) (64-bit)
Watch-on-LBRY: 1.7.2

**Additional context**
No list appears. "Start Conversion" button greys out but no list appears regardless if CSV or JSON is used.

**Comment by kodxana** [comment]
Fixed in https://github.com/LBRYFoundation/Watch-on-LBRY/pull/67

**Comment by Megaf** [comment]
Doesn't seem to work again.
Tried CSV and CSV converted to JSON.

The button greys out and nothing happens.
![image](https://user-images.githubusercontent.com/6201512/134771213-199e482d-089f-4369-ac02-82b4a4e76109.png)
![image](https://user-images.githubusercontent.com/6201512/134771203-aba8a81a-a131-4ce2-a019-3311d43c2266.png)

**Comment by Megaf** [comment]
I tried with the extension from the "Addons stores" and built from the repo.
In both Firefox and Chrome.

**Comment by gi-yt** [comment]
Any clue what is going on? I am having same issue.
Edit: i am using Watch-on-lbry from the webstore on brave

**Comment by kodxana** [comment]
Fixed in https://github.com/LBRYFoundation/Watch-on-LBRY/pull/70
