### ISSUE TITLE
Firefox Addon description links to the wrong GitHub Repo

### ISSUE THREAD

**Issue by WolfIcefang** [LBRYFoundation/Watch-on-LBRY#96]
**Describe the bug**

I had an issue with the Watch-on-LBRY app a couple of weeks ago, and so I went to the extension's webpage of Firefox Add-ons. Unfortunately, the Firefox Add-ons page has the wrong GitHub URL in its description.
![image](https://user-images.githubusercontent.com/38160450/150002395-265ddb06-26fe-4f64-b2fa-0ab9824a58d3.png)

![image](https://user-images.githubusercontent.com/38160450/150002549-ff3dd5cc-5d18-4fb5-ac31-e931fdcd17da.png)

**To Reproduce**
A: if you are using Firefox:
1. Right click on the Watch on LBRY extension and choose "Manage Extension" from the dropdown list.
2. Note that the extension's description says " You can check source code here: https://github.com/kodxana/Watch-on-LBRY " instead of https://github.com/LBRYFoundation/Watch-on-LBRY/

B: If you aren't using firefox:
1. Go to https://addons.mozilla.org/en-US/firefox/addon/watch-on-lbry/
2. Note that the extension description says " You can check source code here: https://github.com/kodxana/Watch-on-LBRY " instead of https://github.com/LBRYFoundation/Watch-on-LBRY/

**Expected behavior**
According to Kodxana, their fork is the wrong repo. https://github.com/kodxana/Watch-on-Odysee/issues/16

**Screenshots**

**Desktop (please complete the following information):**
 - OS: I'm on Windows right now but I prefer/recommend Kubuntu Linux.
 - Browser I'm on Firefox but the Firefox add-ons website loads in Microsoft Edge and probably other browsers too.
 - Version: My Watch on LBRY extension is Version 1.7.6 Last Updated 2022-01-11

**Additional context**
I need to re-rest the issue I had in the other fork to see if it is still broken.

**Comment by kodxana** [comment]
Fixed :)
